### ISSUE TITLE
RepoLib-Specific Deb822 Fields

### ISSUE THREAD

**Issue by kevdogg** [natesales/repo#6]
Hey trying to pull q with ansible, and it doesn't like the one-line style format for your apt repo.  It absolutely hates the gpt --armour choking because of the non-UTF output.

Anyway I've ran across Jeff Geerling talking about the other format known as Deb822: https://repolib.readthedocs.io/en/latest/deb822-format.html

Problem is I don't know how to complete it:

Here is what I have so far (not working):

Suites:
Components: InRelease
Enabled: yes
X-Repolib-Name: natesales
Signed-By: /usr/shares/keyrings/natescales.gpg.key
Trusted: yes
Types: deb
URIs: https://repo.natesales.net/apt

I don't know the Suites, Components no the Repolib-Name.  
Anyway to help me out on this one?

**Comment by kevdogg** [comment]
Here's what's kinda working for me know -- non Deb822 Style for ansible:

```
- name: Get natescales asc key
  ansible.builtin.get_url:
    url: "https://repo.natesales.net/apt/gpg.key"
    dest: /etc/apt/keyrings/natesales.asc
    mode: '0644'
    force: true
    checksum: sha256:20a6bee8bd6e30a8f373476d2bd94ed88aab182123b003a68baf2b5c90392f83

- name: Insert repository into apt.sources.list.d
  ansible.builtin.apt_repository:
    filename: natescales
    repo:  'deb [signed-by=/etc/apt/keyrings/natesales.asc] https://repo.natesales.net/apt * *'
    update_cache: true
  register: install_q_result

- name: Install additional packages
  ansible.builtin.apt:
    name: "{{ extra_debian_repository_packages }}"
    state: present
  when:
    - install_q_result == 0 or  install_q_result is not failed
```
